- name: Create argocd namespace
  kubernetes.core.k8s:
    name: '{{ argocd_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Create argocd directory
  ansible.builtin.file:
    path: '{{ argocd_download_dest_folder }}' 
    state: directory

- name: Download argocd deployment
  get_url:
    url: '{{ argocd_url }}'
    dest: '{{ argocd_download_deployment_file }}' 
    mode: '0440'

- name: Download argocd deployment
  get_url:
    url: '{{ argocd_url }}'
    dest: '{{ argocd_download_deployment_file }}' 
    mode: '0440'

- name: Apply Argo CD installation file  
  kubernetes.core.k8s:
    state: present
    namespace: '{{ argocd_namespace }}'
    src: '{{ argocd_download_deployment_file }}' 
